In [ ]:
grid = [[0,1,2],
        [3,4,5],
        [6,7,8],]

grid = [[1,0,0],
        [0,1,0],
        [0,0,2],]

reshape3 = lambda s: [[s[j + i*3] for j in range(3)] for i in range(0,3)]
flatten3 = lambda s: [j for i in s for j in i]

g  = [0]*9

def is_win(g, p):
    if g[0] == p and g[1] == p and g[2] == p:
        return True
    if g[3] == p and g[4] == p and g[5] == p:
        return True
    if g[6] == p and g[7] == p and g[8] == p:
        return True
    
    if g[0] == p and g[3] == p and g[6] == p:
        return True
    if g[1] == p and g[4] == p and g[7] == p:
        return True
    if g[2] == p and g[5] == p and g[8] == p:
        return True

    if (g[0] == p and g[4] == p and g[8] == p) or (g[6] == p and g[4] == p and g[2] == p):
        return True

    return False

def any_win_on_this_turn(g, p):
    for i in range(len(g)):
        if g[i] == 0:
            g[i] = p
            if is_win(g,p):
                return True
            g[i] = 0
    return False



print(flatten3(grid))
print(any_win_on_this_turn(flatten3(grid), 1))

[1, 0, 0, 0, 1, 0, 0, 0, 2]
False


In [ ]:
import numpy as np

M = [[1,1,1,1,0],
     [1,1,0,1,0],
     [1,1,1,1,1],]

# gridbase = [[0,1,2],
#            [3,4,5],
#            [6,7,8],]

def get_coord_from_m(m):
    out = set()
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i,j))
    return out



coordinates = get_coord_from_m(M)
grid = [0]*len(coordinates)
d = dict()
backd = dict()
t = 0

for i in coordinates:
    d[i] = t
    backd[t] = i
    t+=1

def extract_m_from_grid_directly(g):
    s = set()
    for i in range(len(g)):
        s.add(backd[i])

    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]

    t = np.zeros((maxx-minx+1, maxy-miny+1), dtype = int)
    for i in s:
        t[i[0]-minx][i[1]-miny] = g[d[i]]+1
    return t



def check_this_triplets(s):
    out = set()
    for x, y in s:
        if (x+1,y-1) in s and (x+2,y-2) in s:
            out.add((d[(x,y)],d[(x+1,y-1)], d[(x+2,y-2)]))

        if (x+1,y) in s and (x+2,y) in s:
            out.add((d[(x,y)],d[(x+1,y)], d[(x+2,y)]))
        
        if (x+1,y+1) in s and (x+2,y+2) in s:
            out.add((d[(x,y)],d[(x+1,y+1)], d[(x+2,y+2)]))

        if (x,y+1) in s and (x,y+2) in s:
            out.add((d[(x,y)],d[(x,y+1)], d[(x,y+2)]))
    return out 

triplets = tuple(check_this_triplets(coordinates))
# print(triplets)

def is_win(g, p):
    if any(all(g[j] == p for j in i) for i in triplets):
        return True
    else:
        return False


def win_on_this_turn(g, p):
    for i in range(len(g)):
        if g[i] == 0:
            tempgrid = g.copy()
            tempgrid[i] = p
            if is_win(tempgrid, p):
                return True
    return False

min_turns = []

def exist_a_winning_strat(gridn, n=0, p=1):

    if all(j != 0 for j in gridn): #if draw return None
        return None

    if win_on_this_turn(gridn, p): #if win in one turn exists
        return True

    c = True
    count = 0

    for i in range(len(gridn)):
        if gridn[i] == 0:
            count += 1

            tempgrid = gridn.copy()
            tempgrid[i] = p
            temp = exist_a_winning_strat(tempgrid, n + 1, 1 if p == 2 else 2) 

            if temp is False:
                return True

            if temp is None:
                c = False

    if n == 1:
        print(gridn,)

    if c is True and count > 0:
        return False

    return None


print('win strategy exists: ', exist_a_winning_strat(grid, 0, 1))
# print('min turn: ', min(min_turns))


[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
win strategy exists:  True


In [ ]:
import numpy as np

M = [[1,1,1,1,0],
     [1,1,0,0,0],
     [1,1,1,1,0],]

# gridbase = [[0,1,2],
#            [3,4,5],
#            [6,7,8],]

def get_coord_from_m(m):
    out = set()
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i,j))
    return out



coordinates = get_coord_from_m(M)
grid = [0]*len(coordinates)
d = dict()
backd = dict()
t = 0

for i in coordinates:
    d[i] = t
    backd[t] = i
    t+=1

def extract_m_from_grid_directly(g):
    s = set()
    for i in range(len(g)):
        s.add(backd[i])

    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]

    t = np.zeros((maxx-minx+1, maxy-miny+1), dtype = int)
    for i in s:
        t[i[0]-minx][i[1]-miny] = g[d[i]]+1
    return t



def check_this_triplets(s):
    out = set()
    for x, y in s:
        if (x+1,y-1) in s and (x+2,y-2) in s:
            out.add((d[(x,y)],d[(x+1,y-1)], d[(x+2,y-2)]))

        if (x+1,y) in s and (x+2,y) in s:
            out.add((d[(x,y)],d[(x+1,y)], d[(x+2,y)]))
        
        if (x+1,y+1) in s and (x+2,y+2) in s:
            out.add((d[(x,y)],d[(x+1,y+1)], d[(x+2,y+2)]))

        if (x,y+1) in s and (x,y+2) in s:
            out.add((d[(x,y)],d[(x,y+1)], d[(x,y+2)]))
    return out 

triplets = tuple(check_this_triplets(coordinates))
# print(triplets)

def is_win(g, p):
    if any(all(g[j] == p for j in i) for i in triplets):
        return True
    else:
        return False


def win_on_this_turn(g, p):
    for i in range(len(g)):
        if g[i] == 0:
            tempgrid = g.copy()
            tempgrid[i] = p
            if is_win(tempgrid, p):
                return True
    return False

min_turns = []

def exist_a_winning_strat(gridn, n=0, p=1):

    if all(j != 0 for j in gridn): #if draw return None
        return None

    if win_on_this_turn(gridn, p): #if win in one turn exists
        return True

    c = True
    count = 0

    for i in range(len(gridn)):
        if gridn[i] == 0:
            count += 1

            tempgrid = gridn.copy()
            tempgrid[i] = p
            temp = exist_a_winning_strat(tempgrid, n + 1, 1 if p == 2 else 2) 

            if temp is False:
                return True

            if temp is None:
                c = False

    if n == 1:
        print(extract_m_from_grid_directly(gridn),)

    if c is True and count > 0:
        return False

    return None

for i in range(len(grid)):
    tg = grid.copy()
    tg[i]=1
    if not exist_a_winning_strat(tg, 0, 2):
        print('win strategy exists for secod player: ', False)
        break
else:
    print('win strategy exists for secod player: ', True)

#print('win strategy exists for secod player: ', )
# print('min turn: ', min(min_turns))


[[1 2 3 1]
 [1 1 0 0]
 [1 1 1 1]]
win strategy exists for secod player:  False


In [ ]:
import numpy as np

M = [[1,1,1,1,0],
     [1,1,0,0,0],
     [1,1,1,1,0],]

# gridbase = [[0,1,2],
#            [3,4,5],
#            [6,7,8],]


def has_a_second_p_winstr(M):
    def get_coord_from_m(m):
        out = set()
        for i in range(len(m)):
            for j in range(len(m[i])):
                if  m[i][j] != 0:
                    out.add((i,j))
        return out



    coordinates = get_coord_from_m(M)
    grid = [0]*len(coordinates)
    d = dict()
    backd = dict()
    t = 0

    for i in coordinates:
        d[i] = t
        backd[t] = i
        t+=1

    def extract_m_from_grid_directly(g):
        s = set()
        for i in range(len(g)):
            s.add(backd[i])

        minx = min(s, key = lambda t:t[0])[0]
        maxx = max(s, key = lambda t:t[0])[0]
        miny = min(s, key = lambda t:t[1])[1]
        maxy = max(s, key = lambda t:t[1])[1]

        t = np.zeros((maxx-minx+1, maxy-miny+1), dtype = int)
        for i in s:
            t[i[0]-minx][i[1]-miny] = g[d[i]]+1
        return t



    def check_this_triplets(s):
        out = set()
        for x, y in s:
            if (x+1,y-1) in s and (x+2,y-2) in s:
                out.add((d[(x,y)],d[(x+1,y-1)], d[(x+2,y-2)]))

            if (x+1,y) in s and (x+2,y) in s:
                out.add((d[(x,y)],d[(x+1,y)], d[(x+2,y)]))
            
            if (x+1,y+1) in s and (x+2,y+2) in s:
                out.add((d[(x,y)],d[(x+1,y+1)], d[(x+2,y+2)]))

            if (x,y+1) in s and (x,y+2) in s:
                out.add((d[(x,y)],d[(x,y+1)], d[(x,y+2)]))
        return out 

    triplets = tuple(check_this_triplets(coordinates))
    # print(triplets)

    def is_win(g, p):
        if any(all(g[j] == p for j in i) for i in triplets):
            return True
        else:
            return False


    def win_on_this_turn(g, p):
        for i in range(len(g)):
            if g[i] == 0:
                tempgrid = g.copy()
                tempgrid[i] = p
                if is_win(tempgrid, p):
                    return True
        return False

    min_turns = []

    def exist_a_winning_strat(gridn, n=0, p=1):

        if all(j != 0 for j in gridn): #if draw return None
            return None

        if win_on_this_turn(gridn, p): #if win in one turn exists
            return True

        c = True
        count = 0

        for i in range(len(gridn)):
            if gridn[i] == 0:
                count += 1

                tempgrid = gridn.copy()
                tempgrid[i] = p
                temp = exist_a_winning_strat(tempgrid, n + 1, 1 if p == 2 else 2) 

                if temp is False:
                    return True

                if temp is None:
                    c = False

        # if n == 1:
        #     print(extract_m_from_grid_directly(gridn),)

        if c is True and count > 0:
            return False

        return None

    for i in range(len(grid)):
        tg = grid.copy()
        tg[i]=1
        if not exist_a_winning_strat(tg, 0, 2):
            return False
            break
    else:
        return True



In [ ]:
from random import random
from tqdm import tqdm

def generate_random_m(n, p):
    m = [ [1 if random() < p/(n**2) else 0 for i in range(n)] for j in range(n)]
    return m
flattenlist = lambda s: [j for i in s for j in i]


for i in tqdm(range(1000000)):
    m = generate_random_m(5, 9)
    if 7 < sum(flattenlist(m)) < 14:
        if has_a_second_p_winstr(m):
            print(m)
            break

  0%|          | 202/1000000 [1:37:32<8046:18:22, 28.97s/it]


KeyboardInterrupt: ignored

In [ ]:
import numpy as np

M = [[1,1,1,0,0],
     [1,0,1,1,1],
     [1,1,1,0,1],]

# gridbase = [[0,1,2],
#            [3,4,5],
#            [6,7,8],]

def win_str_exists(m):

    def get_coord_from_m(m):
        out = set()
        for i in range(len(m)):
            for j in range(len(m[i])):
                if  m[i][j] != 0:
                    out.add((i,j))
        return out



    coordinates = get_coord_from_m(M)
    grid = [0]*len(coordinates)
    d = dict()
    backd = dict()
    t = 0

    for i in coordinates:
        d[i] = t
        backd[t] = i
        t+=1

    def extract_m_from_grid_directly(g):
        s = set()
        for i in range(len(g)):
            s.add(backd[i])

        minx = min(s, key = lambda t:t[0])[0]
        maxx = max(s, key = lambda t:t[0])[0]
        miny = min(s, key = lambda t:t[1])[1]
        maxy = max(s, key = lambda t:t[1])[1]

        t = np.zeros((maxx-minx+1, maxy-miny+1), dtype = int)
        for i in s:
            t[i[0]-minx][i[1]-miny] = g[d[i]]+1
        return t



    def check_this_triplets(s):
        out = set()
        for x, y in s:
            if (x+1,y-1) in s and (x+2,y-2) in s:
                out.add((d[(x,y)],d[(x+1,y-1)], d[(x+2,y-2)]))

            if (x+1,y) in s and (x+2,y) in s:
                out.add((d[(x,y)],d[(x+1,y)], d[(x+2,y)]))
            
            if (x+1,y+1) in s and (x+2,y+2) in s:
                out.add((d[(x,y)],d[(x+1,y+1)], d[(x+2,y+2)]))

            if (x,y+1) in s and (x,y+2) in s:
                out.add((d[(x,y)],d[(x,y+1)], d[(x,y+2)]))
        return out 

    triplets = tuple(check_this_triplets(coordinates))
    # print(triplets)

    def is_win(g, p):
        if any(all(g[j] == p for j in i) for i in triplets):
            return True
        else:
            return False


    def win_on_this_turn(g, p):
        for i in range(len(g)):
            if g[i] == 0:
                tempgrid = g.copy()
                tempgrid[i] = p
                if is_win(tempgrid, p):
                    return True
        return False

    min_turns = []

    def exist_a_winning_strat(gridn, n=0, p=1):

        if all(j != 0 for j in gridn): #if draw return None
            return None

        if win_on_this_turn(gridn, p): #if win in one turn exists
            return True

        c = True
        count = 0

        for i in range(len(gridn)):
            if gridn[i] == 0:
                count += 1

                tempgrid = gridn.copy()
                tempgrid[i] = p
                temp = exist_a_winning_strat(tempgrid, n + 1, 1 if p == 2 else 2) 

                if temp is False:
                    return True

                if temp is None:
                    c = False

        # if n == 1:
        #     print(gridn,)

        if c is True and count > 0:
            return False
        return None

    return (exist_a_winning_strat(grid, 0, 1))



In [ ]:
from random import random
from tqdm import tqdm

def generate_random_m(n, p):
    m = [ [1 if random() < p/(n**2) else 0 for i in range(n)] for j in range(n)]
    return m
flattenlist = lambda s: [j for i in s for j in i]


for i in tqdm(range(1000000)):
    m = generate_random_m(4, 9)
    print(np.array(m))
    if 7 < sum(flattenlist(m)) < 16:
        if win_str_exists(m):
            print(m)
            

  0%|          | 0/1000000 [00:00<?, ?it/s]

[[1 1 1 1]
 [1 1 1 0]
 [1 1 0 0]
 [1 0 0 1]]


  0%|          | 1/1000000 [01:22<22952:44:19, 82.63s/it]

[[0 1 0 0]
 [1 1 1 0]
 [1 1 0 0]
 [1 0 0 0]]
[[1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [1 0 0 0]]


  0%|          | 3/1000000 [02:45<14519:04:37, 52.27s/it]

[[1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [1 1 1 1]]


  0%|          | 4/1000000 [04:08<17470:50:58, 62.90s/it]

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 1]]


  0%|          | 5/1000000 [05:31<19282:36:31, 69.42s/it]

[[1 1 1 1]
 [0 1 0 0]
 [0 0 0 0]
 [1 1 1 0]]


  0%|          | 5/1000000 [05:35<18632:40:19, 67.08s/it]


KeyboardInterrupt: ignored

In [ ]:
def mle(M,S):
    #where M is the number of observations and S is the number of distinct observations.
    lower, upper = S, -((M*S-2*S+1)//(S-M)) # Upper bound is an exercise for the code reviewer
    while upper != lower + 1:
        next = (lower + upper)//2
        if (next-1)**M > (next-S)*next**(M-1): # No floating point errors here
            lower = next
        else:
            upper = next
    return lower

mle(10**7, 70000)

In [ ]:
c = [1, 2, 1, 1, 0, 0, 2, 0, 1, 2, 0, 2, 1, 1, 3, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 1, 3, 0, 0, 2, 0, 2, 0, 0, 2, 2, 1, 2, 1, 1, 1, 1, 0, 0, 2, 2, 2, 0, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 2, 0, 0, 1, 2, 2, 0, 3, 0, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 0, 2, 0, 1, 0, 1, 0, 3, 0, 1, 1, 0, 1, 0, 0, 2, 2, 2, 0, 2, 1]

print(''.join(map(str, c)))

1211002012021130000022111101013002020022121111002220211100201220012203011011210222020101030110100222021
