In [ ]:
from tqdm import tqdm
import numpy as np
from random import randint, choice, shuffle, sample, random

def generate_random_m(n, p):
    m = [ [1 if random() < p/(n**2) else 0 for i in range(n)] for j in range(n)]
    return m

def generate_random_m_exactly(n, p):
    p = sample(range(n**2), p)

    m = [ [1 if (i + j*n) in p else 0 for i in range(n)] for j in range(n)]
    return m
M = generate_random_m_exactly(5, 6)


# M = [[0,0,0,1],
#      [0,0,0,1],
#      [1,1,0,0],
#      [0,1,0,0]]

print(np.array(M))

def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t =  [[0]*(maxy-miny+1) for  i in  range(maxx-minx+1)]
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

def generate_rotrefl(tile):
    tile = np.array(tile)
    out = [tile.tolist(),]
    
    #if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    return out


def get_coord_from_m(m):
    out = set()
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i,j))
    return out

def all_displacements(s):
    out = []
    for x,y in s:
        out.append(set(((a-x, b-y) for a,b in s)) )
    return out

def gen_b(t):
    s = generate_rotrefl(t)
    out = []
    for i in s:
        out.extend(all_displacements(get_coord_from_m(i)))
    return out



all_rot = list(map(get_coord_from_m, generate_rotrefl(M)))
print(all_rot)

BigNeven = 4
BigNodd = 5

Bothn  = 2
Dist = 4

def random_xor_of(n):
    p = tuple((randint(0,  len(all_rot)-1), randint(0, Dist), randint(0, Dist)) for _ in range(n))

    s = set()

    for i in p:
        t = set(((a-i[1], b-i[2]) for a, b  in all_rot[i[0]]))
        s  = s ^ t
    
    return p, s


mins =  100000000
iters  = 10**6
collecteven = set()
collectodd = set()

dists = set()

for i in tqdm(range(iters)):

    par, xors = random_xor_of(BigNeven)

    if len(xors) == Bothn:
        t = extract_m_from_set_directly(xors)

        if str(t) not in collecteven:

            distt =  np.linalg.norm( np.array(list(xors)[0]) - np.array(list(xors)[1]) )

            #print(distt)
            collecteven.update(map(str, generate_rotrefl(t)))

            print('\n', np.array(t))
            print(par)

print('DONE!!!!')

for i in tqdm(range(iters)):

    par, xors = random_xor_of(BigNodd)

    if len(xors) == Bothn :
        t = extract_m_from_set_directly(xors)
        if str(t) not in collectodd:

            collectodd.update(map(str, generate_rotrefl(t)))

            # print('\n', np.array(t))
            print('\n', np.array(t))
            print(par)

# print(len(collecteven), len(collectodd))
# print(collecteven & collectodd)


# 101 ((4, 4, 1), (1, 4, 3), (3, 4, 3), (0, 4, 2))


[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]]
[{(3, 2), (3, 0), (3, 1), (2, 1), (2, 2), (0, 2)}, {(3, 2), (3, 3), (2, 3), (2, 2), (3, 4), (0, 2)}, {(1, 2), (1, 3), (2, 0), (2, 3), (2, 2), (0, 3)}, {(3, 2), (3, 3), (2, 0), (2, 3), (4, 3), (2, 2)}, {(3, 2), (3, 1), (2, 1), (2, 2), (4, 1), (2, 4)}, {(1, 2), (1, 3), (1, 4), (2, 3), (2, 2), (4, 2)}, {(1, 2), (2, 1), (2, 2), (4, 2), (1, 0), (1, 1)}, {(0, 1), (1, 2), (2, 1), (2, 4), (2, 2), (1, 1)}]


 37%|███▋      | 367529/1000000 [00:13<00:22, 27800.37it/s]


 [[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]]
((0, 2, 2), (5, 3, 2), (4, 2, 3), (2, 2, 2))


 47%|████▋     | 465812/1000000 [00:16<00:19, 27134.58it/s]


 [[1]
 [0]
 [1]]
((1, 2, 1), (7, 2, 0), (5, 2, 1), (4, 2, 0))


100%|██████████| 1000000/1000000 [00:36<00:00, 27603.92it/s]



 [[1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]]
((5, 0, 3), (3, 3, 2), (6, 2, 1), (1, 1, 3))
DONE!!!!


100%|██████████| 1000000/1000000 [00:45<00:00, 22030.25it/s]


In [ ]:
from tqdm import tqdm
import numpy as np
from random import randint, choice, shuffle, sample, random




def generate_random_m(n, p):
    m = [ [1 if random() < p/(n**2) else 0 for i in range(n)] for j in range(n)]
    return m

def generate_rotrefl(tile):
    tile = np.array(tile)
    out = [tile.tolist(),]
    
    #if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    tile = np.rot90(tile)

    if tile.tolist() not in out:out.append(tile.tolist())
    if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
    if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())

    return out


def random_polyominoe(n):
    from random import choice
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),))
    s = set(((0,0),))
    sn =  near(0,0)
    for i in range(n-1):
        t = choice(tuple(sn))
        s.add(t)
        sn = (sn | near(t[0], t[1])) - s
    return s 


def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t = np.zeros((maxx-minx+1, maxy-miny+1), dtype = int)
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

def get_coord_from_m(m):
    out = set()
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i,j))
    return out

def all_displacements(s):
    out = []
    for x,y in s:
        out.append(set(((a-x, b-y) for a,b in s)) )
    return out

def gen_b(t):
    s = generate_rotrefl(t)
    out = []
    for i in s:
        out.extend(all_displacements(get_coord_from_m(i)))
    return out

BigN = 5
Dist =  6

for tt  in range(10000):

    #M = generate_random_m(4, 8)
    #print(np.array(M))
    M = extract_m_from_set_directly(random_polyominoe(8))

    print(M.tolist())

    all_rot = list(map(get_coord_from_m, generate_rotrefl(M)))


    def random_xor_of(n):
        p = tuple((randint(0,  len(all_rot)-1), randint(0, Dist), randint(0, Dist)) for _ in range(n))

        s = set()

        for i in p:
            t = set(((a-i[1], b-i[2]) for a, b  in all_rot[i[0]]))
            s  = s ^ t
        
        return p, s


    mins =  100000000
    minp = []

    for i in range( 10**6):

        par, xors = random_xor_of(BigN)

        if len(xors)< mins:
            # print('\n')
            mins = len(xors)
            minp  = par
            # print(mins, par )
        
            if len(xors)  == 0:
                # print(')))))')
                # print(par, xors)
                break

    print( mins,  minp)

    if mins == 0:
        break


    



# for i in tqdm(range(100000000)):
#     M = generate_random_m(4, 10)
#     t = gen_b(M)
    

    



[[0, 1, 0], [1, 1, 0], [0, 1, 1], [1, 1, 0], [0, 1, 0]]


KeyboardInterrupt: ignored

In [ ]:
from tqdm import tqdm
import numpy as np

def random_polyomino(n):
    from random import choice
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),))
    s = set(((0,0),))
    sn =  near(0,0)

    for i in range(n-1):
        t = choice(tuple(sn))
        s.add(t)
        sn = (sn | near(t[0], t[1])) - s
    return s 
    
t = random_polyomino(8)
out = '$'.join(map(str, extract_m_from_set_directly(t)))

def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t =  [[0]*(maxy-miny+1) for  i in  range(maxx-minx+1)]
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

8
[0, 1, 1]$[1, 1, 1]$[1, 0, 1]$[0, 0, 1]


In [ ]:
import sys
sys.setrecursionlimit(15000)


def random_polyomino(n):
    from random import choice
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),))
    s = set(((0,0),))
    sn =  near(0,0)

    for i in range(n-1):
        t = choice(tuple(sn))
        s.add(t)
        sn = (sn | near(t[0], t[1])) - s
    return s 

def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t =  [[0]*(maxy-miny+1) for  i in  range(maxx-minx+1)]
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

def has_a_hole(K):
    from copy import deepcopy
    M = deepcopy(K)
    d1  =  len(M)
    d2  =  len(M[0])
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)

    def start_from_seed(x,y, M):
        if not(0 <= x < d1 and 0 <= y < d2)  or M[x][y] != 0 :
            return
        M[x][y] = 3
        for dx, dy in near(x, y):
            start_from_seed(dx, dy, M)

    for i in range(d1):
        start_from_seed(i, 0, M)
        start_from_seed(i, d2-1, M)
    for i in range(d2):
        start_from_seed(0,i, M)
        start_from_seed(d1-1, i, M)

    f = any(any(j == 0 for j in i) for i in M)
    return f

def connected_tile(s):
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    count = 0
    
    def start_from_seed(x,y):
        if not(0 <= x < d1 and 0 <= y < d2)  or (x,y) not in s :
            return
        count += 1
        for dx, dy in near(x, y):
            start_from_seed(dx, dy)

    start_from_seed(tuple(s)[0])

    return count == len(s)
    
        




# T = [[0,0,1,1],
#      [1,0,0,1],
#      [1,0,0,1],
#      [1,1,1,1]]

for i in range(1):
    P = random_polyomino(7)
    T = extract_m_from_set_directly(P)

    h = has_a_hole(T)
    if h:
        print('\n[', ',\n  '.join(map(str, T)), ']')


In [ ]:
def random_polyomino_walk(n):
    from random import choice
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),))
    t = (0,0)
    s = set((t,))
    r = 0
    while r < (n-1):
        sn = near(*t) - s
        if len(sn) == 0:
            t = choice(tuple(s))
        else:
            t = choice(tuple(sn))
            r+=1
            s.add(t)
    return s 

for i in range(10):
    P = random_polyomino_walk(100)
    T = extract_m_from_set_directly(P)

    h = has_a_hole(T)
    if h:
        #print(len(T), len(T[0]))
        print('\n[', ',\n  '.join(map(str, T)), ']')


In [ ]:
T = [[0,1,1,1],
     [1,0,0,1],
     [1,0,0,1],
     [1,1,1,1]]

def get_coord_from_m(m):
    out = set()
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i,j))
    return out

def get_neighbourhood(s):
    out = s.copy()
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),(x+1,y+1),(x+1,y-1),(x-1,y-1),(x-1,y-1),))
    for i in s:
        out = out | near(*i)
    return out-s 

def connected_tile(k):
    s = k.copy()
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    def start_from_seed(x,y):
        if (x,y) not in s:
            return
        s.discard((x,y))
        for dx, dy in near(x, y):
            start_from_seed(dx, dy)
    start_from_seed(*tuple(s)[0])
    return len(s) == 0

def has_a_hole(s):
    return not connected_tile(get_neighbourhood(s))

print(has_a_hole(get_coord_from_m(T)))


True


In [ ]:
import numpy as np

T1 = [[1,1,1],
      [1,0,1],
      [1,0,1],]

T2 = [[1,0],
      [1,1],]

tiles = [T1, ]

def generate_rotrefl(tile):
    out = []
    tile = np.array(tile)
    for j in range(6):
        tile = np.rot90(tile)
        if tile.tolist() not in out:out.append(tile.tolist())
        if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
        if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())
    return out

def has_a_hole(K):
    from copy import deepcopy
    M = deepcopy(K)
    d1  =  len(M)
    d2  =  len(M[0])
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)

    def start_from_seed(x,y, M):
        if not(0 <= x < d1 and 0 <= y < d2)  or M[x][y] != 0 :
            return
        M[x][y] = 3
        for dx, dy in near(x, y):
            start_from_seed(dx, dy, M)

    for i in range(d1):
        start_from_seed(i, 0, M)
        start_from_seed(i, d2-1, M)
    for i in range(d2):
        start_from_seed(0,i, M)
        start_from_seed(d1-1, i, M)

    f = any(any(j == 0 for j in i) for i in M)
    return f

def get_coord_from_m(m):
    out = set()
    orig = (0,0)
    c = 0
    for i in range(len(m)):
        if c == 1:break
        for j in range(len(m[i])):
            if m[i][j] != 0:
                c=1
                orig = (i,j)
                break
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i-orig[0],j-orig[0]))
                
    return out

def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t =  [[0]*(maxy-miny+1) for  i in  range(maxx-minx+1)]
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

def get_neighbourhood(s):
    out = s.copy()
    def near(x,y):
        return set(((x,y+1),(x+1,y),))
    for i in s:
        out = out | near(*i)
    return out-s 

def gen_batch(tiles):
    out = []
    for i in tiles:
        for j in generate_rotrefl(i):
            dt = get_coord_from_m(j)
            out.append((dt, get_neighbourhood(dt)))
    return out


tiles = [j for i in tiles for j in generate_rotrefl(i)]
tiles_sets =[(get_coord_from_m(i), get_neighbourhood(get_coord_from_m(i))) for i in tiles]


def draw_from_tset(p):
    s = []
    for i in range(len(p)):
        t = tiles_sets[p[i][0]][0]
        for a,b in t:
            s.append((a + p[i][1],b + p[i][2], i+1))
    minx, maxx = min(s, key = lambda t:t[0])[0], max(s, key = lambda t:t[0])[0]
    miny, maxy = min(s, key = lambda t:t[1])[1], max(s, key = lambda t:t[1])[1]
    t = np.zeros((maxx-minx + 1 , maxy-miny + 1), dtype = int)
    for i in s: t[i[0]-minx][i[1]-miny] = i[2]
    return t.tolist()

near = lambda x,y: set(((x+1,y), (x,y+1)))

def tile_rect(n,m, tiles):
    global border

    grid = set([(i,j) for i in range(n) for j in range(m)])
    border = set()
    for i in range(n):
        border.add((i, 0))
        # border.add((i, m-1))
    for i in range(m):
        border.add((0,i))
        # border.add((n-1, i))

    global out
    global end
    global memo

    end = []
    out = []
    memo = set()

    def dfs(grid, pattern, neighbourhood, p):
        
        if len(end) > 0:
            return

        # if pattern != set():
        #     g = extract_m_from_set_directly(pattern)
        #     print('\n[', ',\n  '.join(map(str, g)), ']')
        if pattern != set():
            h = extract_m_from_set_directly(pattern)

            if pattern != set() and has_a_hole(h):
                return

            if grid == set():
                out.append(p)
                end.append(1)
                return

            sh = ''.join(''.join(map(str, i)) for i in h) 

            if sh in memo:
                return
            else:
                memo.add(sh)

        if grid & border != set():
            for x,y in neighbourhood & border:
                for r in range(len(tiles)):
                    t = tiles[r]
                    tempt = set((x+t1,y+t2) for t1, t2 in t[0])
                    if len(tempt-grid) == 0:
                        temp_p = p.copy()
                        tempnear = set((x+t1,y+t2) for t1, t2 in t[1])
                        temp_p.append((r, x, y))
                        temp_pattern = pattern |  tempt
                        tempgrid = grid - tempt
                        dfs(tempgrid,  temp_pattern, ((neighbourhood | tempnear) - temp_pattern) & tempgrid, temp_p)
        else:
            for x,y in neighbourhood:
                for r in range(len(tiles)):
                    t = tiles[r]
                    tempt = set((x+t1,y+t2) for t1, t2 in t[0])
                    if len(tempt-grid) == 0:
                        temp_p = p.copy()
                        tempnear = set((x+t1,y+t2) for t1, t2 in t[1])
                        temp_p.append((r, x, y))
                        temp_pattern = pattern |  tempt
                        tempgrid = grid - tempt
                        dfs(tempgrid,  temp_pattern, ((neighbourhood | tempnear) - temp_pattern) & tempgrid, temp_p)


    dfs(grid, set(), set(((0,0),)), []) 

    return out



solution = tile_rect(2, 7, tiles_sets)

print(solution)
if solution != []:
    ms = draw_from_tset(solution[0])
    print('[', ',\n  '.join(map(str, ms)) , '],',)



[]


In [ ]:
M = [[1,1,1],
     [1,0,1],
     [1,1,1],]

s = get_coord_from_m(M)

def get_neighbourhood(s):
    out = s.copy()
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),(x+1,y+1),(x+1,y-1),(x-1,y-1),(x-1,y-1),))
    for i in s:
        out = out | near(*i)
    return out-s 

def fast_hole1(s):
    s = get_neighbourhood(s)
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x-1,y),(x,y-1),(x+1,y+1),(x+1,y-1),(x-1,y-1),(x-1,y-1),))
    for i in s:
        #print(len(near(*i) & s))
        if len(near(*i) & s) == 0:
            return True
    return False

fast_hole1(s)


In [ ]:
M = [[1,1,1,1,1],
     [1,1,0,1,1],
     [1,0,1,0,1],
     [1,1,1,1,1],
     [1,1,1,0,0],]

def print_m(M):
    print('[', ',\n  '.join(map(str, M)) , '],',)

def get_border(K):
    from copy import deepcopy
    M = deepcopy(K)
    d1  =  len(M)
    d2  =  len(M[0])
    def near(x,y): return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    def start_from_seed(x,y,M):
        if not(0 <= x < d1 and 0 <= y < d2) or M[x][y] == 2 or M[x][y] == 3: return
        if M[x][y] == 1:
            M[x][y] = 2
            return
        M[x][y] = 3
        for dx, dy in near(x, y):
            start_from_seed(dx, dy, M)
    for i in range(d1):
        start_from_seed(i, 0, M)
        start_from_seed(i, d2-1, M)
    for i in range(d2):
        start_from_seed(0,i, M)
        start_from_seed(d1-1, i, M)
    for x in range(len(M)):
        for y in range(len(M[0])):
            if M[x][y] == 2: 
                M[x][y] = 1
            else: 
                M[x][y] = 0
    return M

print_m(get_border(M))

[ [1, 1, 1, 1, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 1, 1],
  [1, 1, 1, 0, 0] ],


In [ ]:
def connected_tile(k):
    s = k.copy()
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    def start_from_seed(x,y):
        if (x,y) not in s:
            return
        s.discard((x,y))
        for dx, dy in near(x, y):
            start_from_seed(dx, dy)
    start_from_seed(*tuple(s)[0])
    return len(s) == 0

def tile_rect(n,m, tiles):
    global border
    maxntest = 20000

    grid = set([(i,j) for i in range(n) for j in range(m)])
    border = set()
    for i in range(n):
        border.add((i, 0))
        # border.add((i, m-1))
    for i in range(m):
        border.add((0,i))
        # border.add((n-1, i))

    global out
    global end
    global memo

    end = []
    out = []
    memo = set()

    def dfs(grid, pattern, neighbourhood, p):
        
        if len(end) > 0:
            return

        # if pattern != set():
        #     g = extract_m_from_set_directly(pattern)
        #     print('\n[', ',\n  '.join(map(str, g)), ']')
        if pattern != set():
            h = extract_m_from_set_directly(pattern)

            # if pattern != set() and has_a_hole(h):
            #     return

            if grid != set() and not connected_tile(grid):
                return

            if grid == set():
                out.append(p)
                end.append(1)
                return

            sh = ''.join(''.join(map(str, i)) for i in h) 

            if sh in memo:
                return
            else:
                memo.add(sh)

        if grid & border != set():
            for x,y in neighbourhood & border:
                for r in range(len(tiles)):
                    t = tiles[r]
                    tempt = set((x+t1,y+t2) for t1, t2 in t[0])
                    if len(tempt-grid) == 0:
                        temp_p = p.copy()
                        tempnear = set((x+t1,y+t2) for t1, t2 in t[1])
                        temp_p.append((r, x, y))
                        temp_pattern = pattern |  tempt
                        tempgrid = grid - tempt
                        dfs(tempgrid,  temp_pattern, ((neighbourhood | tempnear) - temp_pattern) & tempgrid, temp_p)
        else:
            iterstest = 0
            
            for x,y in neighbourhood:
                if iterstest > maxntest:break
                for r in range(len(tiles)):
                    if iterstest > maxntest:break
                    t = tiles[r]
                    tempt = set((x+t1,y+t2) for t1, t2 in t[0])
                    if len(tempt-grid) == 0:
                        iterstest +=1
                        temp_p = p.copy()
                        tempnear = set((x+t1,y+t2) for t1, t2 in t[1])
                        temp_p.append((r, x, y))
                        temp_pattern = pattern |  tempt
                        tempgrid = grid - tempt
                        dfs(tempgrid,  temp_pattern, ((neighbourhood | tempnear) - temp_pattern) & tempgrid, temp_p)


    dfs(grid, set(), set(((0,0),)), []) 

    return out

for c in range(2, 100):

    D1 = c
    D2 = 28

    solution = tile_rect(D1, D2, tiles_sets)

    
    print(solution)
    if solution != []:
        print(D1, D2, len(solution[0]))
        ms = draw_from_tset(solution[0])
        print('[', ',\n  '.join(map(str, ms)) , '],',)


In [1]:
import numpy as np

T1 = [[1,0,0],
      [1,1,0],
      [0,0,0],]

T2 = [[1,0],
      [1,1],]

tiles = [T1, T2]

def generate_rotrefl(tile):
    out = []
    tile = np.array(tile)
    for j in range(6):
        tile = np.rot90(tile)
        if tile.tolist() not in out:out.append(tile.tolist())
        if np.fliplr(tile).tolist() not in out:out.append(np.fliplr(tile).tolist())
        if np.transpose(tile).tolist() not in out:out.append(np.transpose(tile).tolist())
    return out

def get_coord_from_m(m):
    out = set()
    orig = (0,0)
    c = 0
    for i in range(len(m)):
        if c == 1:break
        for j in range(len(m[i])):
            if m[i][j] != 0:
                c=1
                orig = (i,j)
                break
    for i in range(len(m)):
        for j in range(len(m[i])):
            if  m[i][j] != 0:
                out.add((i-orig[0],j-orig[0]))
                
    return out

def get_neighbourhood(s):

    out = s.copy()
    def near(x,y):
        return set(((x,y+1),(x+1,y),(x,y-1),(x-1,y)))
    for i in s:
        out = out | near(*i)
    return out-s 

def extract_m_from_set_directly(s):
    minx = min(s, key = lambda t:t[0])[0]
    maxx = max(s, key = lambda t:t[0])[0]
    miny = min(s, key = lambda t:t[1])[1]
    maxy = max(s, key = lambda t:t[1])[1]
    t =  [[0]*(maxy-miny+1) for  i in  range(maxx-minx+1)]
    for i in s:t[i[0]-minx][i[1]-miny] = 1
    return t

def gen_batch(tiles):
    out = []
    for i in tiles:
        for j in generate_rotrefl(i):
            dt = get_coord_from_m(j)
            out.append((dt, get_neighbourhood(dt)))
    return out
    
def connected_tile(k):
    s = k.copy()
    def near(x,y):
        return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    def start_from_seed(x,y):
        if (x,y) not in s:
            return
        s.discard((x,y))
        for dx, dy in near(x, y):
            start_from_seed(dx, dy)
    start_from_seed(*tuple(s)[0])
    return len(s) == 0



def get_border(K):



    from copy import deepcopy
    M = deepcopy(K)
    d1  =  len(M)
    d2  =  len(M[0])
    def near(x,y): return ((x,y+1),(x+1,y),(x-1,y),(x,y-1),)
    def start_from_seed(x,y,M):
        if not(0 <= x < d1 and 0 <= y < d2) or M[x][y] == 2 or M[x][y] == 3: return
        if M[x][y] == 1:
            M[x][y] = 2
            return
        M[x][y] = 3
        for dx, dy in near(x, y):
            start_from_seed(dx, dy, M)
    for i in range(d1):
        start_from_seed(i, 0, M)
        start_from_seed(i, d2-1, M)
    for i in range(d2):
        start_from_seed(0,i, M)
        start_from_seed(d1-1, i, M)
    for x in range(len(M)):
        for y in range(len(M[0])):
            if M[x][y] == 2: 
                M[x][y] = 1
            else: 
                M[x][y] = 0
    return M

tiles = [j for i in tiles for j in generate_rotrefl(i)]
tiles_sets =[(get_coord_from_m(i), get_neighbourhood(get_coord_from_m(i))) for i in tiles]

def print_m(M):
    print('[', ',\n  '.join(map(str, M)) , '],',)

def tile_rect(n,m, tiles):
    global border
    maxntest = 20000

    grid = set([(i,j) for i in range(n) for j in range(m)])
    border = set()
    for i in range(n):
        border.add((i, 0))
        # border.add((i, m-1))
    for i in range(m):
        border.add((0,i))
        # border.add((n-1, i))

    global out
    global end
    global memo

    end = []
    out = []
    memo = set()

    def dfs(grid, border, pattern, neighbourhood, p, n):
        
        
        if len(end) > 0:
            return

        if pattern != set():
            
            h = extract_m_from_set_directly(pattern)

            print(n)
            print_m(h)

            # if pattern != set() and has_a_hole(h):
            #     return

            if grid != set() and not connected_tile(grid):
                return

            if grid == set():
                out.append(p)
                end.append(1)
                return

            # sh = int(''.join(''.join(map(str, i)) for i in h) )

            # if sh in memo:
            #     return
            # else:
            #     memo.add(sh)

        if grid & border != set():
            for x,y in neighbourhood & border:
                for r in range(len(tiles)):
                    t = tiles[r]
                    tempt = set((x+t1,y+t2) for t1, t2 in t[0])
                    if len(tempt-grid) == 0:
                        temp_p = p.copy()
                        tempnear = set((x+t1,y+t2) for t1, t2 in t[1])
                        temp_p.append((r, x, y))
                        temp_pattern = pattern |  tempt
                        tempgrid = grid - tempt
                        dfs(tempgrid, border,  temp_pattern, ((neighbourhood | tempnear) - temp_pattern) & tempgrid, temp_p, n+1)
        else:
            tempborder = get_coord_from_m(get_border(extract_m_from_set_directly(grid)))

            print_m(get_border(extract_m_from_set_directly(grid)))

            dfs(grid, tempborder, pattern, neighbourhood, p, n)


    startborder =  get_coord_from_m(get_border(extract_m_from_set_directly(grid)))
    dfs(grid, startborder, set(), set(((0,0),)), [], 0) 

    return out



solution = tile_rect(3, 6, tiles_sets)

print(solution)
if solution != []:
    ms = draw_from_tset(solution[0])
    print('[', ',\n  '.join(map(str, ms)) , '],',)


Выходные данные были обрезаны до нескольких последних строк (5000).
4
[ [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
4
[ [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
3
[ [1, 1, 0, 1, 1],
  [1, 1, 0, 1, 0],
  [1, 1, 0, 0, 0] ],
4
[ [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
3
[ [1, 1, 0, 1, 1],
  [0, 1, 1, 1, 0],
  [0, 1, 1, 0, 0] ],
3
[ [1, 1, 0, 1, 1],
  [1, 1, 0, 1, 0],
  [1, 1, 0, 0, 0] ],
4
[ [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
3
[ [1, 1, 0, 1, 1],
  [1, 1, 0, 1, 0],
  [1, 1, 0, 0, 0] ],
4
[ [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
2
[ [1, 1, 1, 1],
  [0, 1, 0, 1] ],
3
[ [1, 1, 1, 1],
  [1, 1, 0, 1],
  [1, 1, 0, 0] ],
4
[ [1, 1, 1, 1, 1, 0],
  [1, 1, 0, 1, 1, 1],
  [1, 1, 0, 0, 0, 0] ],
4
[ [1, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 0, 1],
  [1, 1, 0, 0, 0, 0] ],
4
[ [1, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 0, 1],
  [1, 1, 0, 0, 0, 0] ],
4
[ [1, 1, 1, 1, 1, 0],
  [1, 1, 0, 1, 1